# Site settings
title: SPARTAN
description: Strategic Platform for Autonomous Resilient and Trusted Agents @ NUS
baseurl: ""
url: "https://spartan-nus.github.io"

# Build settings
markdown: kramdown

# Exclude from processing
exclude:
  - node_modules
  - .github
  - README.md
  - vendor
  - Gemfile
  - Gemfile.lock

# NUS colors
colors:
  blue: "#003D7C"
  orange: "#EF7C00"
